apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    app: appointment
spec:
  selector:
    app: appointment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP

