apiVersion: v1
kind: Service
metadata:
  name: patient-service
  labels:
    app: patient
spec:
  selector:
    app: patient
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

